services:
  postgres:
    container_name: postgres-delivery
    image: postgres
    environment:
      POSTGRES_USER: delivery
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
  pgadmin:
    container_name: pgadmin-delivery
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-azerty}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin-delivery
    ports:
      - "9411:9411"
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq-delivery
    ports:
      - "5672:5672"
      - "15672:15672"




networks:
  postgres:
    driver: bridge
volumes:
  postgres:
  pgadmin: