server:
  port: 8084
spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: foodItem
          uri: lb://FOODITEM
          predicates:
            - Path=/api/v1/food/**



        - id: category
          uri: lb://FOODITEM
          predicates:
            - Path=/api/v2/category/**


        - id: restaurant
          uri: lb://FOODITEM
          predicates:
            - Path=/api/v2/restaurant/**

        - id: order
          uri: lb://ORDER
          predicates:
            - Path=/api/v3/orders/**
          filters:
            - name: AuthFilter


        - id: notification
          uri: lb://NOTIFICATION
          predicates:
            - Path=notification/**
          filters:
            - name: AuthFilter


        - id : users
          uri : lb://USERS
          predicates:
            - Path=/api/v1/auth/**




eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true