server:
  port: 8081

management:
  tracing:
    sampling:
      probability: 1.0


spring:
  application:
    name: foodItem
  main:
    web-application-type: reactive
  datasource:
    url: jdbc:postgresql://localhost:5432/foodItem
    username: delivery
    password: password


  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
      show-sql: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  cloud:
    gateway:
      routes:
        - id: foodItem
          uri: lb://FOODITEM
          predicates:
            - Path=/api/v1/food/**
        - id: category
          uri: lb://FOODITEM
          predicates:
            - Path=/api/v2/category/**
        - id: restaurant
          uri: lb://FOODITEM
          predicates:
            - Path=/api/v2/restaurant/**

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

