server:
  port: 8081




spring:
  application:
    name: foodItem
  datasource:
    url: jdbc:postgresql://localhost:5432/foodItem
    username: delivery
    password: password


  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
      show-sql: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

