server:
  port: 8082

spring:
  application:
    name: Order
  datasource:
    url: jdbc:postgresql://localhost:5432/order
    username: delivery
    password: password


  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
      show-sql: true
  rabbitmq:
    addresses: localhost:5672


management:
  tracing:
    sampling:
      probability: 1.0


eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true