server:
  port: 8085

spring:
  application:
    name: users
  datasource:
    url: jdbc:postgresql://localhost:5432/users
    username: delivery
    password: passfinal


  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
      show-sql: true

app:
  jwtSecret: 442A472D4B6150645367566B59703373367639792442264528482B4D6251655468576D5A7134743777217A25432A462D4A404E635266556A586E327235753878

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true


